---
dist: focal
language: python
python: "3.9"
os: linux
services:
  - docker

install:
  - pip install -I pipenv
  - pipenv sync
env:
  - MOLECULE_DISTRO=debian:buster-slim FILEBEAT_VERSION=8.9.0
  - MOLECULE_DISTRO=debian:bullseye-slim FILEBEAT_VERSION=8.9.0
  - MOLECULE_DISTRO=debian:buster-slim FILEBEAT_VERSION=7.17.12
  - MOLECULE_DISTRO=debian:bullseye-slim FILEBEAT_VERSION=7.17.12
script:
  - pipenv run molecule test --all

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
