---
- name: Filebeat | Starting service
  systemd:
    name: filebeat
    state: "{{ filebeat_service_state }}"
    enabled: "{{ filebeat_service_enabled }}"
    daemon_reload: true
  register: filebeat_service_output
